- name: play with tags
  hosts: web_servers
  gather_facts: false

  tasks:
  - name: task1 (Update cache)
    tags: update
    apt:
      update_cache: true

  - name: task2 (Install latest nginx)
    tags: install, always
    apt:
      name: nginx
      state: latest